name: Deploy Static Site

on:
  push:
    branches:
      - main  # ou "master" se sua branch principal for master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./   # raiz do repositório, se sua index.html estiver aqui
          # ou ajuste se estiver em "dist/", "build/" etc

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
